### ISSUE TITLE
GetPath 可以接多个参数拼接成目录

### ISSUE THREAD

**Issue by jiangxin** [Jiu2015/gotestspace#2]
1. 建议 GetPath 的参数做一下 `filepath.Clean`。防止 `repo.git\\refs` 这样的路径在 Linux 下报错
2. GetPath 可以接多个参数，用 `filepath.Join` 拼接。

**Comment by Jiu2015** [comment]
已经在 93ca9c2 中添加了 `GetMultiPath` 方法来接多个参数拼接
